// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmTransaction = `-- name: ConfirmTransaction :exec
UPDATE rampx_cross_chain_swaps 
SET tx_status = $1
WHERE transaction_hash = $2
`

type ConfirmTransactionParams struct {
	TxStatus        TxStatus
	TransactionHash string
}

func (q *Queries) ConfirmTransaction(ctx context.Context, arg ConfirmTransactionParams) error {
	_, err := q.db.Exec(ctx, confirmTransaction, arg.TxStatus, arg.TransactionHash)
	return err
}

const createSwapOrder = `-- name: CreateSwapOrder :exec
INSERT INTO rampx_cross_chain_swaps (
  source_chain, destination_chain, source_token, destination_token, source_amount, destination_amount, dollar_value, source_address, destination_address, tx_status, transaction_hash
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
`

type CreateSwapOrderParams struct {
	SourceChain        int32
	DestinationChain   int32
	SourceToken        string
	DestinationToken   string
	SourceAmount       pgtype.Numeric
	DestinationAmount  pgtype.Numeric
	DollarValue        pgtype.Numeric
	SourceAddress      string
	DestinationAddress string
	TxStatus           TxStatus
	TransactionHash    string
}

func (q *Queries) CreateSwapOrder(ctx context.Context, arg CreateSwapOrderParams) error {
	_, err := q.db.Exec(ctx, createSwapOrder,
		arg.SourceChain,
		arg.DestinationChain,
		arg.SourceToken,
		arg.DestinationToken,
		arg.SourceAmount,
		arg.DestinationAmount,
		arg.DollarValue,
		arg.SourceAddress,
		arg.DestinationAddress,
		arg.TxStatus,
		arg.TransactionHash,
	)
	return err
}

const getDailyVolume = `-- name: GetDailyVolume :many
SELECT 
    DATE(tx_timestamp) as trade_date,
    COUNT(*) as number_of_trades,
    SUM(dollar_value) as total_daily_volume
FROM rampx_cross_chain_swaps
WHERE 
    tx_timestamp >= CURRENT_DATE - INTERVAL '30 days'
    AND status = 'COMPLETED'
GROUP BY DATE(tx_timestamp)
ORDER BY trade_date DESC
`

type GetDailyVolumeRow struct {
	TradeDate        pgtype.Date
	NumberOfTrades   int64
	TotalDailyVolume int64
}

func (q *Queries) GetDailyVolume(ctx context.Context) ([]GetDailyVolumeRow, error) {
	rows, err := q.db.Query(ctx, getDailyVolume)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyVolumeRow
	for rows.Next() {
		var i GetDailyVolumeRow
		if err := rows.Scan(&i.TradeDate, &i.NumberOfTrades, &i.TotalDailyVolume); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingTransactions = `-- name: GetPendingTransactions :many
SELECT 
    transaction_hash,
    source_chain,
    destination_chain,
    tx_timestamp
FROM rampx_cross_chain_swaps
WHERE tx_status = 'PROCESSING'
ORDER BY tx_timestamp DESC 
LIMIT 190
`

type GetPendingTransactionsRow struct {
	TransactionHash  string
	SourceChain      int32
	DestinationChain int32
	TxTimestamp      pgtype.Timestamp
}

func (q *Queries) GetPendingTransactions(ctx context.Context) ([]GetPendingTransactionsRow, error) {
	rows, err := q.db.Query(ctx, getPendingTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingTransactionsRow
	for rows.Next() {
		var i GetPendingTransactionsRow
		if err := rows.Scan(
			&i.TransactionHash,
			&i.SourceChain,
			&i.DestinationChain,
			&i.TxTimestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
