// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type TxStatus string

const (
	TxStatusINITIATED  TxStatus = "INITIATED"
	TxStatusPROCESSING TxStatus = "PROCESSING"
	TxStatusCOMPLETED  TxStatus = "COMPLETED"
	TxStatusFAILED     TxStatus = "FAILED"
)

func (e *TxStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TxStatus(s)
	case string:
		*e = TxStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TxStatus: %T", src)
	}
	return nil
}

type NullTxStatus struct {
	TxStatus TxStatus
	Valid    bool // Valid is true if TxStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTxStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TxStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TxStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTxStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TxStatus), nil
}

type RampxCrossChainSwap struct {
	SwapID             int64
	SourceChain        int32
	DestinationChain   int32
	SourceToken        string
	DestinationToken   string
	SourceAmount       pgtype.Numeric
	DestinationAmount  pgtype.Numeric
	DollarValue        pgtype.Numeric
	SourceAddress      string
	DestinationAddress string
	TxTimestamp        pgtype.Timestamp
	TxStatus           TxStatus
	TransactionHash    string
}

type RampxSwapStatistic struct {
	StatID        int64
	StatDate      pgtype.Date
	TotalVolume   pgtype.Numeric
	NumberOfSwaps int32
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}
