// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserWallet = `-- name: AddUserWallet :exec
INSERT INTO rampx_user_wallets (
    user_name,
    chain_id,
    user_address
) VALUES (
    $1, $2, $3
)
`

type AddUserWalletParams struct {
	UserName    string
	ChainID     int64
	UserAddress string
}

func (q *Queries) AddUserWallet(ctx context.Context, arg AddUserWalletParams) error {
	_, err := q.db.Exec(ctx, addUserWallet, arg.UserName, arg.ChainID, arg.UserAddress)
	return err
}

const confirmTransaction = `-- name: ConfirmTransaction :exec
UPDATE rampx_cross_chain_swaps 
SET tx_status = $1
WHERE transaction_hash = $2
`

type ConfirmTransactionParams struct {
	TxStatus        TxStatus
	TransactionHash string
}

func (q *Queries) ConfirmTransaction(ctx context.Context, arg ConfirmTransactionParams) error {
	_, err := q.db.Exec(ctx, confirmTransaction, arg.TxStatus, arg.TransactionHash)
	return err
}

const createSwapOrder = `-- name: CreateSwapOrder :exec
SELECT insert_cross_chain_swap(
    source_chain_id := $1,
    source_token_address := $2,
    source_amount := $3,
    destination_chain_id := $4,
    destination_token_address := $5,
    destination_amount := $6,
    dollar_value := $7,
    fee_dollar_value := $8,
    source_address := $9,
    destination_address := $10,
    tx_status := 'COMPLETED',
    transaction_hash := $11
)
`

type CreateSwapOrderParams struct {
	SourceChainID           int64
	SourceTokenAddress      string
	SourceAmount            pgtype.Numeric
	DestinationChainID      int64
	DestinationTokenAddress string
	DestinationAmount       pgtype.Numeric
	DollarValue             pgtype.Numeric
	FeeDollarValue          pgtype.Numeric
	SourceAddress           string
	DestinationAddress      string
	TransactionHash         string
}

func (q *Queries) CreateSwapOrder(ctx context.Context, arg CreateSwapOrderParams) error {
	_, err := q.db.Exec(ctx, createSwapOrder,
		arg.SourceChainID,
		arg.SourceTokenAddress,
		arg.SourceAmount,
		arg.DestinationChainID,
		arg.DestinationTokenAddress,
		arg.DestinationAmount,
		arg.DollarValue,
		arg.FeeDollarValue,
		arg.SourceAddress,
		arg.DestinationAddress,
		arg.TransactionHash,
	)
	return err
}

const getDailyVolume = `-- name: GetDailyVolume :many
SELECT 
    DATE(tx_timestamp) as trade_date,
    COUNT(*) as number_of_trades,
    SUM(dollar_value) as total_daily_volume,
    SUM(fee_dollar_value) as total_daily_fee_volume
FROM rampx_cross_chain_swaps
WHERE 
    tx_timestamp >= CURRENT_DATE - INTERVAL '30 days'
    AND status = 'COMPLETED'
GROUP BY DATE(tx_timestamp)
ORDER BY trade_date DESC
`

type GetDailyVolumeRow struct {
	TradeDate           pgtype.Date
	NumberOfTrades      int64
	TotalDailyVolume    int64
	TotalDailyFeeVolume int64
}

func (q *Queries) GetDailyVolume(ctx context.Context) ([]GetDailyVolumeRow, error) {
	rows, err := q.db.Query(ctx, getDailyVolume)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyVolumeRow
	for rows.Next() {
		var i GetDailyVolumeRow
		if err := rows.Scan(
			&i.TradeDate,
			&i.NumberOfTrades,
			&i.TotalDailyVolume,
			&i.TotalDailyFeeVolume,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExistingWalletsByChainAndAddress = `-- name: GetExistingWalletsByChainAndAddress :one
SELECT count(*) from rampx_user_wallets
WHERE 
    chain_id = $1 AND 
    user_address ILIKE $2
`

type GetExistingWalletsByChainAndAddressParams struct {
	ChainID     int64
	UserAddress string
}

func (q *Queries) GetExistingWalletsByChainAndAddress(ctx context.Context, arg GetExistingWalletsByChainAndAddressParams) (int64, error) {
	row := q.db.QueryRow(ctx, getExistingWalletsByChainAndAddress, arg.ChainID, arg.UserAddress)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getExistingWalletsByUsername = `-- name: GetExistingWalletsByUsername :one
SELECT count(*) from rampx_user_wallets
WHERE 
    user_name ILIKE $1
`

func (q *Queries) GetExistingWalletsByUsername(ctx context.Context, userName string) (int64, error) {
	row := q.db.QueryRow(ctx, getExistingWalletsByUsername, userName)
	var count int64
	err := row.Scan(&count)
	return count, err
}
